function EEG = addChan(EEG,chanLocs)
% add a channel with no data; this does NOT affect the size of EEG.data

chanLabel = chanLocs.labels;

%
EEG = pop_chanedit(EEG, 'append',1,'changefield',{2,'labels',chanLabel},...
    'changefield',{2,'theta',chanLocs.theta},...
    'changefield',{2,'radius',chanLocs.radius},...
    'changefield',{2,'X',chanLocs.X},...
    'changefield',{2,'Y',chanLocs.Y},...
    'changefield',{2,'Z',chanLocs.Z},...
    'changefield',{2,'sph_theta',chanLocs.sph_theta},...
    'changefield',{2,'sph_phi',chanLocs.sph_phi},...
    'changefield',{2,'sph_radius',chanLocs.sph_radius});


% add relevant comments
s = sprintf('%s ',chanLabel);
EEG = MEEGtools.addComments(EEG,sprintf('Channel(s) %s added',s));

end
%
%